export const MOCK_PRODUCTS = [
  {
    _id: 'prod_1',
    name: 'Aura SoundPro Wireless Noise-Canceling Headphones',
    slug: 'aura-soundpro-wireless-headphones',
    description: 'Immerse yourself in crystal clear audio with active noise cancellation, 35-hour battery life, and ultra-plush memory foam earcups.',
    price: 249.99,
    discountPrice: 199.99,
    discountPercent: 20,
    category: 'electronics',
    rating: 4.8,
    numReviews: 124,
    stock: 45,
    isFeatured: true,
    isTrending: true,
    isNew: false,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['audio', 'wireless', 'headphones'],
    specifications: [
      { name: 'Connectivity', value: 'Bluetooth 5.3 / 3.5mm Jack' },
      { name: 'Battery Life', value: '35 Hours with ANC' },
      { name: 'Weight', value: '250g' },
    ],
  },
  {
    _id: 'prod_2',
    name: 'Zenith Smart Watch Series 7 Pro',
    slug: 'zenith-smart-watch-series-7-pro',
    description: 'Track your health metrics, heart rate, sleep quality, and daily activities with an ultra-bright AMOLED display and 7-day battery life.',
    price: 329.00,
    discountPrice: 289.00,
    discountPercent: 12,
    category: 'electronics',
    rating: 4.7,
    numReviews: 89,
    stock: 28,
    isFeatured: true,
    isTrending: true,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['wearable', 'smartwatch', 'fitness'],
    specifications: [
      { name: 'Display', value: '1.9" Always-On AMOLED' },
      { name: 'Water Resistance', value: '50m (5 ATM)' },
      { name: 'Sensors', value: 'ECG, SpO2, Heart Rate' },
    ],
  },
  {
    _id: 'prod_3',
    name: 'Urban Minimalist Leather Backpack',
    slug: 'urban-minimalist-leather-backpack',
    description: 'Crafted from full-grain genuine leather with a dedicated 15-inch laptop compartment, water-resistant lining, and ergonomic shoulder straps.',
    price: 149.50,
    discountPrice: 119.50,
    discountPercent: 20,
    category: 'fashion',
    rating: 4.9,
    numReviews: 210,
    stock: 15,
    isFeatured: true,
    isTrending: false,
    isNew: false,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['backpack', 'leather', 'fashion'],
    specifications: [
      { name: 'Material', value: '100% Full Grain Cowhide Leather' },
      { name: 'Capacity', value: '22 Liters' },
      { name: 'Laptop Compartment', value: 'Up to 15.6 inches' },
    ],
  },
  {
    _id: 'prod_4',
    name: 'Luminary Ergonomic Task Chair',
    slug: 'luminary-ergonomic-task-chair',
    description: 'Engineered for all-day comfort with breathable mesh back, adjustable lumbar support, 4D armrests, and synchro-tilt mechanism.',
    price: 399.00,
    discountPrice: 349.00,
    discountPercent: 13,
    category: 'home',
    rating: 4.6,
    numReviews: 64,
    stock: 12,
    isFeatured: false,
    isTrending: true,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1580481072645-022f9a6d8310?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['furniture', 'chair', 'office'],
    specifications: [
      { name: 'Weight Capacity', value: '300 lbs' },
      { name: 'Frame Material', value: 'Reinforced Aluminum' },
    ],
  },
  {
    _id: 'prod_5',
    name: 'Velocity Ultra-Light Running Shoes',
    slug: 'velocity-ultra-light-running-shoes',
    description: 'Designed for high performance and maximum comfort. Breathable flyknit upper with responsive foam cushioning for effortless strides.',
    price: 129.99,
    discountPrice: 99.99,
    discountPercent: 23,
    category: 'sports',
    rating: 4.8,
    numReviews: 142,
    stock: 50,
    isFeatured: true,
    isTrending: true,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['shoes', 'running', 'sports'],
    specifications: [
      { name: 'Upper', value: 'Engineered Flyknit Mesh' },
      { name: 'Sole', value: 'High-Grip Rubber' },
    ],
  },
  {
    _id: 'prod_6',
    name: 'Botanica Organic Hydrating Facial Serum',
    slug: 'botanica-organic-hydrating-facial-serum',
    description: 'Infused with pure Hyaluronic Acid, Vitamin C, and Botanical Extracts to restore skin radiance and deeply hydrate without grease.',
    price: 48.00,
    discountPrice: 38.00,
    discountPercent: 21,
    category: 'beauty',
    rating: 4.9,
    numReviews: 312,
    stock: 80,
    isFeatured: true,
    isTrending: false,
    isNew: false,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['skincare', 'serum', 'organic'],
    specifications: [
      { name: 'Volume', value: '50 ml / 1.7 fl oz' },
      { name: 'Skin Type', value: 'All Skin Types' },
    ],
  },
  {
    _id: 'prod_7',
    name: 'Precision Mechanical Keyboard RGB',
    slug: 'precision-mechanical-keyboard-rgb',
    description: 'Custom hot-swappable mechanical switches with per-key RGB backlighting, double-shot PBT keycaps, and durable aluminum top frame.',
    price: 119.00,
    discountPrice: 99.00,
    discountPercent: 17,
    category: 'electronics',
    rating: 4.7,
    numReviews: 76,
    stock: 35,
    isFeatured: false,
    isTrending: true,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['keyboard', 'gaming', 'pc'],
    specifications: [
      { name: 'Switch Type', value: 'Linear Red Switches' },
      { name: 'Keycaps', value: 'PBT Double Shot' },
    ],
  },
  {
    _id: 'prod_8',
    name: 'Artisan Ceramic Pour-Over Coffee Set',
    slug: 'artisan-ceramic-pour-over-coffee-set',
    description: 'Handcrafted ceramic coffee dripper and carafe set with matte black finish. Delivers rich, aromatic pour-over coffee every morning.',
    price: 65.00,
    discountPrice: 55.00,
    discountPercent: 15,
    category: 'home',
    rating: 4.9,
    numReviews: 95,
    stock: 22,
    isFeatured: true,
    isTrending: false,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ],
    tags: ['coffee', 'kitchen', 'ceramic'],
    specifications: [
      { name: 'Capacity', value: '600 ml (approx. 4 cups)' },
      { name: 'Dishwasher Safe', value: 'Yes' },
    ],
  }
];

export const MOCK_REVIEWS = [
  {
    _id: 'rev_1',
    productId: 'prod_1',
    userName: 'Alex Johnson',
    userAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'The noise cancellation on these headphones is unmatched! Battery life easily lasts me through 3 full workdays.',
    createdAt: '2026-09-15T10:30:00Z',
  },
  {
    _id: 'rev_2',
    productId: 'prod_1',
    userName: 'Sophia Martinez',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    rating: 4,
    comment: 'Super comfortable fit and sound quality is rich. The companion app equalizer makes a noticeable difference.',
    createdAt: '2026-09-10T14:15:00Z',
  },
];

export const MOCK_USER = {
  _id: 'user_1',
  name: 'John Doe',
  email: 'john@example.com',
  role: 'user', // 'user' or 'admin'
  phone: '+1 (555) 234-5678',
  address: {
    street: '123 Market Street, Suite 400',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94105',
    country: 'USA',
  },
};

export const MOCK_ADMIN_USER = {
  _id: 'admin_1',
  name: 'Admin Manager',
  email: 'admin@shopsphere.com',
  role: 'admin',
  phone: '+1 (555) 999-0000',
  address: {
    street: '1 Enterprise Way',
    city: 'San Jose',
    state: 'CA',
    postalCode: '95110',
    country: 'USA',
  },
};

export const MOCK_ORDERS = [
  {
    _id: 'ORD-98214',
    createdAt: '2026-09-28T09:20:00Z',
    items: [
      {
        product: MOCK_PRODUCTS[0],
        quantity: 1,
        price: 199.99,
      },
      {
        product: MOCK_PRODUCTS[5],
        quantity: 2,
        price: 38.00,
      }
    ],
    shippingAddress: {
      fullName: 'John Doe',
      phone: '+1 (555) 234-5678',
      address: '123 Market Street, Suite 400',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94105',
    },
    paymentMethod: 'Credit Card',
    paymentStatus: 'Paid',
    orderStatus: 'Shipped',
    subtotal: 275.99,
    tax: 22.08,
    shippingCost: 0,
    discount: 10.00,
    totalAmount: 288.07,
    trackingNumber: 'TRK-88392019',
  },
  {
    _id: 'ORD-98102',
    createdAt: '2026-09-14T16:45:00Z',
    items: [
      {
        product: MOCK_PRODUCTS[2],
        quantity: 1,
        price: 119.50,
      }
    ],
    shippingAddress: {
      fullName: 'John Doe',
      phone: '+1 (555) 234-5678',
      address: '123 Market Street, Suite 400',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94105',
    },
    paymentMethod: 'PayPal',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    subtotal: 119.50,
    tax: 9.56,
    shippingCost: 5.00,
    discount: 0,
    totalAmount: 134.06,
    trackingNumber: 'TRK-77491028',
  }
];

export const MOCK_ADMIN_STATS = {
  totalUsers: 1420,
  totalProducts: 86,
  totalOrders: 324,
  totalRevenue: 48920.50,
  recentOrders: MOCK_ORDERS,
  topProducts: MOCK_PRODUCTS.slice(0, 4),
};
